apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blog-frontend
  description: Blog Frontend
  tags:
    - java
    - spring
    - web
    - blog
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=blog-frontend'
spec:
  type: service
  lifecycle: experimental
  owner: making
