apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: note-api
  namespace: note
  description: Note API
  tags:
    - java
    - spring
    - web
    - note
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=note-api'
spec:
  type: service
  lifecycle: experimental
  owner: making
  system: note
  providesApis:
  - note-api-run.pineapple.maki.lol
